### ISSUE TITLE
Expired certificate on https://genome-cancer.ucsc.edu/

### ISSUE THREAD

**Issue by yurivict** [ucscXena/ucsc-xena-server#16]
https://genome-cancer.ucsc.edu/download/public/get-xena/index.html.

**Comment by maryjgoldman** [comment]
Not sure if it's related but the link on the View My Data page is also down
![Screen Shot 2019-04-12 at 10 14 44 AM](https://user-images.githubusercontent.com/13877333/56054512-e46ec980-5d0b-11e9-91b0-6b21a35992f0.png)

**Comment by yurivict** [comment]
Yes, it is broken.

**Comment by maryjgoldman** [comment]
@yurivict Thanks for the report! We're working on it
