### ISSUE TITLE
please specify JRE version compatible with cavm jar file

### ISSUE THREAD

**Issue by zmiimz** [ucscXena/ucsc-xena-server#18]
> java -jar cavm-0.25.0-standalone.jar --help
WARNING: update already refers to: #'clojure.core/update in namespace: clj-http.client, being replaced by: #'clj-http.client/update
Exception in thread "main" java.lang.ExceptionInInitializerError
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:415)
        at clojure.lang.RT.classForName(RT.java:2154)
...

**Comment by acthp** [comment]
It should work with java 8. Later JREs have not been tested significantly.

That warning about method ```update``` is expected.

**Comment by zmiimz** [comment]
thanks, but I am talking about  Exception error in thread "main" java.lang.ExceptionInInitializerError... in standard java 12 version of the average Linux distribution.

Installers for OSX and windows are packaged into dmg and exe files on the web site, so for Linux case one cannot find out easily the proper JRE version. Please add this info into README or directly on the web page. All old java JREs are deprecated/removed from Linux repositories (due to security, Oracle distribution rules etc), so users have to download and install that JRE manually for Linux.

**Comment by acthp** [comment]
ah, right. Thanks!
